apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1  # Number of desired replicas
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: bounajia/frontend:tagname
          ports:
            - containerPort: 3000  
  ---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      
  
port: 80    # Expose port 80 on the service
      
      
targetPort: 3000   # Route traffic to port 3000 on the pods
  
  
type: ClusterIP   # Expose the service internally within the cluster          
