{
  "kind": "Deployment", 
  "spec": {
    "replicas": 3, 
    "template": {
      "spec": {
        "containers": [
          {
            "image": "my-simple-app", 
            "name": "react-app-container", 
            "ports": [
              {
                "containerPort": 3000
              }
            ]
          }
        ]
      }, 
      "metadata": {
        "labels": {
          "app": "react-app"
        }
      }
    }, 
    "selector": {
      "matchLabels": {
        "app": "react-app"
      }
    }
  }, 
  "apiVersion": "apps/v1", 
  "metadata": {
    "name": "react-app-deployment"
  }
}
