apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-deployment
  labels:
    app: front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
      - name: front
        image: bounajia/frontend-projet:v1.0
        ports:
        - containerPort: 3000
            
---
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: front
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30100
      
